package org.gitee.orryx.module.wiki

import org.gitee.orryx.core.kether.ScriptManager
import taboolib.common.LifeCycle
import taboolib.common.platform.Awake

/**
 * 注册 TabooLib 原版 Kether 语句到 wiki 系统
 */
object NativeKetherWiki {

    @Awake(LifeCycle.ENABLE)
    private fun register() {
        val actions = ScriptManager.wikiActions

        // ========== 控制流 ==========
        val flow = "Kether原生-控制流"
        actions += Action.new(flow, "导入命名空间", "import")
            .addEntry("命名空间名称", Type.STRING).description("导入指定命名空间的语句").example("import Orryx")
        actions += Action.new(flow, "释放命名空间", "release")
            .addEntry("命名空间名称", Type.STRING).description("释放已导入的命名空间")
        actions += Action.new(flow, "暂停脚本", "pause").description("暂停脚本执行（永不完成）")
        actions += Action.new(flow, "终止脚本", "exit").description("终止脚本执行，别名 stop/terminate").example("exit")
        actions += Action.new(flow, "条件分支", "if")
            .addEntry("条件表达式", Type.BOOLEAN)
            .addEntry("then标识", Type.SYMBOL, head = "then")
            .addEntry("条件为真时执行", Type.ANY)
            .addEntry("条件为假时执行", Type.ANY, true, head = "else")
            .description("条件判断，根据条件执行不同分支")
            .example("if check &health > 50 then tell \"健康\" else tell \"虚弱\"")
        actions += Action.new(flow, "布尔取反", "not")
            .addEntry("布尔值", Type.BOOLEAN).description("对布尔值取反").result("取反结果", Type.BOOLEAN)
        actions += Action.new(flow, "重复执行", "repeat")
            .addEntry("重复次数", Type.INT).addEntry("执行的动作", Type.ANY)
            .description("重复执行指定动作 N 次").example("repeat 3 tell \"hello\"")
        actions += Action.new(flow, "异步执行", "async")
            .addEntry("执行的动作", Type.ANY).description("在异步线程中执行动作")
        actions += Action.new(flow, "等待异步", "await")
            .addEntry("异步动作", Type.ANY).description("等待异步 Future 完成并返回结果").result("异步结果", Type.ANY)
        actions += Action.new(flow, "等待全部", "await_all")
            .addEntry("动作列表", Type.ITERABLE).description("等待所有异步 Future 完成")
        actions += Action.new(flow, "等待任一", "await_any")
            .addEntry("动作列表", Type.ITERABLE).description("等待任一异步 Future 完成").result("最先完成的结果", Type.ANY)
        actions += Action.new(flow, "全部为真", "all")
            .addEntry("布尔动作列表", Type.ITERABLE).description("短路与，所有动作结果为 true 时返回 true").result("是否全部为真", Type.BOOLEAN)
        actions += Action.new(flow, "任一为真", "any")
            .addEntry("布尔动作列表", Type.ITERABLE).description("短路或，任一动作结果为 true 时返回 true").result("是否有任一为真", Type.BOOLEAN)
        actions += Action.new(flow, "顺序执行", "seq", true)
            .addEntry("动作列表", Type.ITERABLE).description("顺序执行动作列表，返回最后一个结果").result("最后一个动作的结果", Type.ANY)
        actions += Action.new(flow, "调用Block", "call")
            .addEntry("Block名称", Type.STRING).description("调用指定的 block 并返回结果").result("Block返回值", Type.ANY)
        actions += Action.new(flow, "跳转Block", "goto")
            .addEntry("Block名称", Type.STRING).description("跳转到指定的 block 执行")
        // ========== 输出 ==========
        val output = "Kether原生-输出"
        actions += Action.new(output, "控制台日志", "log")
            .addEntry("日志内容", Type.STRING).description("控制台输出 info 级别日志，别名 print/info").example("log \"hello world\"")
        actions += Action.new(output, "控制台警告", "warn")
            .addEntry("警告内容", Type.STRING).description("控制台输出 warn 级别日志，别名 warning")
        actions += Action.new(output, "控制台错误", "error")
            .addEntry("错误内容", Type.STRING).description("控制台输出 severe 级别日志，别名 severe")
        actions += Action.new(output, "发送消息", "tell")
            .addEntry("消息内容", Type.STRING).description("向执行者发送消息，别名 send/message").example("tell \"你好\"")
        actions += Action.new(output, "ActionBar消息", "actionbar")
            .addEntry("消息内容", Type.STRING).description("向执行者发送 ActionBar 消息")
        actions += Action.new(output, "全服广播", "broadcast")
            .addEntry("广播内容", Type.STRING).description("向全服玩家广播消息，别名 bc")
        actions += Action.new(output, "发送Title", "title")
            .addEntry("标题内容", Type.STRING)
            .addEntry("副标题", Type.STRING, true, head = "subtitle")
            .addEntry("淡入时间", Type.INT, true, head = "by")
            .addEntry("停留时间", Type.INT, true)
            .addEntry("淡出时间", Type.INT, true)
            .description("向执行者发送 Title，by/with 后接三个整数").example("title \"主标题\" subtitle \"副标题\" by 10 40 10")
        actions += Action.new(output, "发送Subtitle", "subtitle")
            .addEntry("副标题内容", Type.STRING)
            .addEntry("淡入时间", Type.INT, true, head = "by")
            .addEntry("停留时间", Type.INT, true)
            .addEntry("淡出时间", Type.INT, true)
            .description("向执行者发送 Subtitle，by/with 后接三个整数")
        // ========== 延迟 ==========
        val delay = "Kether原生-延迟"
        actions += Action.new(delay, "延迟执行", "wait")
            .addEntry("延迟时间(Duration)", Type.LONG)
            .description("延迟执行后续语句，支持 Duration 格式（20/1s/500ms），别名 delay/sleep")
            .example("wait 20").example("wait 1s").example("wait 500ms")
        // ========== 变量 ==========
        val variable = "Kether原生-变量"
        actions += Action.new(variable, "获取变量", "get")
            .addEntry("变量名", Type.STRING).description("获取变量值，也支持 get property <name> from <action> 获取属性").result("变量值", Type.ANY)
            .example("get test").example("get property \"name\" from &player")
        actions += Action.new(variable, "设置变量", "set")
            .addEntry("变量名", Type.STRING)
            .addEntry("to标识", Type.SYMBOL, head = "to")
            .addEntry("变量值", Type.ANY)
            .description("设置变量值，也支持 set property <name> from <action> to <value> 和 set <name>[<key>] to <value>")
            .example("set test to 100").example("set property \"name\" from &player to \"Steve\"")
        actions += Action.new(variable, "空值", "null").description("返回 null 值").result("null", Type.NULL)
        actions += Action.new(variable, "空字符串", "pass").description("返回空字符串").result("空字符串", Type.STRING)
        actions += Action.new(variable, "变量列表", "vars")
            .description("返回当前所有变量名列表，别名 variables").result("变量名列表", Type.ITERABLE)
        // ========== 循环 ==========
        val loop = "Kether原生-循环"
        actions += Action.new(loop, "遍历循环", "for")
            .addEntry("变量名", Type.STRING).addEntry("in标识", Type.SYMBOL, head = "in")
            .addEntry("可迭代对象", Type.ITERABLE).addEntry("then标识", Type.SYMBOL, head = "then")
            .addEntry("循环体", Type.ANY)
            .description("遍历集合/数组/Map").example("for i in range 1 to 10 then tell &i")
        actions += Action.new(loop, "条件循环", "while")
            .addEntry("条件表达式", Type.BOOLEAN).addEntry("then标识", Type.SYMBOL, head = "then")
            .addEntry("循环体", Type.ANY)
            .description("当条件为真时重复执行")
        actions += Action.new(loop, "映射转换", "map")
            .addEntry("变量名", Type.STRING).addEntry("in标识", Type.SYMBOL, head = "in")
            .addEntry("可迭代对象", Type.ITERABLE).addEntry("with标识", Type.SYMBOL, head = "with")
            .addEntry("转换动作", Type.ANY)
            .description("对集合每个元素执行转换，返回新列表").result("转换后的列表", Type.ITERABLE)
        actions += Action.new(loop, "拼接字符串", "join")
            .addEntry("动作列表", Type.ITERABLE)
            .addEntry("分隔符", Type.ANY, true, head = "by")
            .description("将列表拼接为字符串，by/with 后接分隔符").result("拼接结果", Type.STRING)
            .example("join [ \"a\" \"b\" \"c\" ] by \",\"")
        actions += Action.new(loop, "跳出循环", "break").description("跳出当前 for/while 循环")
        // ========== 数学运算 ==========
        val math = "Kether原生-数学"
        actions += Action.new(math, "数学运算", "math")
            .addEntry("运算符(+/-/*/÷)", Type.SYMBOL)
            .addEntry("数值列表", Type.ITERABLE)
            .description("数学四则运算，支持列表模式和链式模式").result("运算结果", Type.DOUBLE)
            .example("math + [ 1 2 3 ]").example("math &a + &b - &c")
        actions += Action.new(math, "表达式计算", "calc")
            .addEntry("JEXL3表达式", Type.STRING)
            .description("使用 JEXL3 引擎计算表达式，别名 calculate，支持 calc dynamic <action>").result("计算结果", Type.ANY)
            .example("calc \"1+2*3\"").example("calc \"&damage * 1.5\"")
        actions += Action.new(math, "随机数", "random")
            .addEntry("值或起始值", Type.ANY)
            .addEntry("结束值", Type.ANY, true, head = "to")
            .description("生成随机数（random <from> to <to>）或从集合中随机取元素（random <collection>），别名 random2").result("随机结果", Type.ANY)
            .example("random 1 to 10").example("random &list")
        actions += Action.new(math, "四舍五入", "round")
            .addEntry("数值", Type.DOUBLE).description("四舍五入取整").result("整数结果", Type.INT)
        actions += Action.new(math, "格式化数字", "scale")
            .addEntry("数值", Type.DOUBLE)
            .description("格式化数字（保留小数位），别名 scaled").result("格式化结果", Type.STRING)
        actions += Action.new(math, "数字范围", "range")
            .addEntry("起始值", Type.DOUBLE).addEntry("to标识", Type.SYMBOL, head = "to")
            .addEntry("结束值", Type.DOUBLE).addEntry("步长", Type.DOUBLE, true, head = "step")
            .description("生成数字范围列表").result("数字列表", Type.ITERABLE)
            .example("range 1 to 10").example("range 0 to 100 step 5")
        actions += Action.new(math, "比较判断", "check")
            .addEntry("左值", Type.ANY).addEntry("比较符", Type.SYMBOL)
            .addEntry("右值", Type.ANY)
            .description("比较两个值，支持 ==/is/!=/not/>/gt/>=/gte/</lt/<=/lte/in/contains/has 等").result("比较结果", Type.BOOLEAN)
            .example("check &health > 50").example("check &name == \"Steve\"")
        // ========== 类型转换 ==========
        val transform = "Kether原生-类型转换"
        actions += Action.new(transform, "类型转换", "type")
            .addEntry("目标类型(int/long/float/double/boolean)", Type.STRING)
            .addEntry("值", Type.ANY)
            .description("将值转换为指定类型，也可用于字面量类型推断").result("转换后的值", Type.ANY)
            .example("type int \"123\"")
        actions += Action.new(transform, "内联函数", "inline")
            .addEntry("Kether函数字符串", Type.STRING)
            .description("内联执行 Kether 函数字符串，别名 function").result("执行结果", Type.ANY)
        actions += Action.new(transform, "空值处理", "optional")
            .addEntry("值", Type.ANY).addEntry("默认值", Type.ANY, true, head = "else")
            .description("如果值为 null 则返回默认值").result("非空结果", Type.ANY)
        actions += Action.new(transform, "模式匹配", "case")
            .addEntry("输入值", Type.ANY)
            .description("模式匹配（when/switch），根据输入值匹配不同分支").result("匹配分支的结果", Type.ANY)
            .example("case &type [ when == \"fire\" then tell \"火\" when == \"ice\" then tell \"冰\" else tell \"未知\" ]")
        actions += Action.new(transform, "正则匹配", "match")
            .addEntry("文本", Type.STRING).addEntry("正则表达式", Type.STRING, head = "by")
            .description("正则表达式匹配，返回 Matcher 对象（可通过 matcher.operator 访问捕获组）").result("Matcher对象", Type.ANY)
        actions += Action.new(transform, "拆分字符串", "split")
            .addEntry("文本", Type.STRING).addEntry("分隔符", Type.STRING, true, head = "by")
            .description("按分隔符拆分字符串，by/with 后接分隔符").result("拆分后的列表", Type.ITERABLE)
            .example("split \"a,b,c\" by \",\"")
        actions += Action.new(transform, "格式化时间", "format")
            .addEntry("时间戳(毫秒)", Type.LONG).addEntry("格式模板", Type.STRING, true, head = "by")
            .description("将时间戳格式化为字符串，by/with 后接格式模板").result("格式化结果", Type.STRING)
            .example("format time by \"yyyy-MM-dd HH:mm:ss\"")
        actions += Action.new(transform, "打字机效果", "printed")
            .addEntry("文本", Type.STRING).addEntry("光标字符", Type.STRING, true, head = "by")
            .description("生成逐字展开的文本列表（打字机效果），by/with 后接光标字符").result("文本列表", Type.ITERABLE)
        // ========== 数组操作 ==========
        val arr = "Kether原生-数组"
        actions += Action.new(arr, "构建列表", "array")
            .addEntry("元素列表", Type.ITERABLE)
            .description("构建一个列表，别名 arr").result("列表", Type.ITERABLE)
            .example("array [ 1 2 3 ]")
        actions += Action.new(arr, "获取长度", "size")
            .addEntry("集合/数组/字符串", Type.ANY)
            .description("获取集合、数组或字符串的长度，别名 length").result("长度", Type.INT)
        actions += Action.new(arr, "转可变列表", "mutable")
            .addEntry("列表", Type.ITERABLE).description("将列表转为可变列表").result("可变列表", Type.ITERABLE)
        actions += Action.new(arr, "打乱列表", "shuffle")
            .addEntry("列表", Type.ITERABLE).description("随机打乱列表顺序").result("打乱后的列表", Type.ITERABLE)
        actions += Action.new(arr, "反转列表", "reverse")
            .addEntry("列表", Type.ITERABLE).description("反转列表顺序").result("反转后的列表", Type.ITERABLE)
        actions += Action.new(arr, "获取元素", "arr-get")
            .addEntry("索引", Type.INT).addEntry("列表", Type.ITERABLE, head = "in")
            .description("获取列表指定索引的元素，别名 element/elem").result("元素", Type.ANY)
            .example("arr-get 0 in &list")
        actions += Action.new(arr, "添加元素", "arr-add")
            .addEntry("元素", Type.ANY).addEntry("列表", Type.ITERABLE, head = "to")
            .description("添加元素到列表末尾")
        actions += Action.new(arr, "头部添加", "arr-add-first")
            .addEntry("元素", Type.ANY).addEntry("列表", Type.ITERABLE, head = "to")
            .description("添加元素到列表开头，别名 arr-push")
        actions += Action.new(arr, "按值移除", "arr-remove")
            .addEntry("元素", Type.ANY).addEntry("列表", Type.ITERABLE, head = "in")
            .description("从列表中按值移除元素")
        actions += Action.new(arr, "按索引移除", "arr-remove-at")
            .addEntry("索引", Type.INT).addEntry("列表", Type.ITERABLE, head = "in")
            .description("从列表中按索引移除元素")
        actions += Action.new(arr, "移除首元素", "arr-remove-first")
            .addEntry("列表", Type.ITERABLE)
            .description("移除并返回列表首个元素，别名 arr-take").result("被移除的元素", Type.ANY)
        actions += Action.new(arr, "移除末元素", "arr-remove-last")
            .addEntry("列表", Type.ITERABLE)
            .description("移除并返回列表末尾元素，别名 arr-drop").result("被移除的元素", Type.ANY)
        actions += Action.new(arr, "查找索引", "arr-find")
            .addEntry("元素", Type.ANY).addEntry("列表", Type.ITERABLE, head = "in")
            .description("查找元素在列表中的索引").result("索引（-1表示未找到）", Type.INT)
        // ========== 时间日期 ==========
        val time = "Kether原生-时间"
        actions += Action.new(time, "当前时间戳", "time")
            .addEntry("格式模板", Type.STRING, true, head = "as")
            .description("获取当前时间戳（毫秒），可格式化输出，别名 date").result("时间戳或格式化字符串", Type.ANY)
            .example("time").example("time as \"yyyy-MM-dd\"")
        actions += Action.new(time, "天数", "day")
            .addEntry("of标识(year/month/week)", Type.STRING, head = "of")
            .description("获取当前天数（年中第几天/月中第几天/周中第几天），别名 days，支持 of/in").result("天数", Type.INT)
        actions += Action.new(time, "当前年份", "year").description("获取当前年份，别名 years").result("年份", Type.INT)
        actions += Action.new(time, "当前月份", "month").description("获取当前月份，别名 months").result("月份", Type.INT)
        actions += Action.new(time, "当前小时", "hour").description("获取当前小时，别名 hours").result("小时", Type.INT)
        actions += Action.new(time, "当前分钟", "minute").description("获取当前分钟，别名 minutes").result("分钟", Type.INT)
        actions += Action.new(time, "当前秒", "second").description("获取当前秒，别名 seconds").result("秒", Type.INT)
        // ========== 游戏交互 ==========
        val game = "Kether原生-游戏"
        actions += Action.new(game, "颜色转换", "color")
            .addEntry("文本", Type.STRING).description("将 & 颜色代码转换为实际颜色，别名 colored").result("着色文本", Type.STRING)
        actions += Action.new(game, "去除颜色", "uncolor")
            .addEntry("文本", Type.STRING).description("去除文本中的颜色代码，别名 uncolored").result("纯文本", Type.STRING)
        actions += Action.new(game, "权限检查", "perm")
            .addEntry("权限节点", Type.STRING).description("检查执行者是否拥有指定权限，别名 permission").result("是否有权限", Type.BOOLEAN)
        actions += Action.new(game, "在线玩家列表", "players")
            .description("获取所有在线玩家名列表").result("玩家名列表", Type.ITERABLE)
        actions += Action.new(game, "执行者名称", "sender")
            .description("获取当前脚本执行者的名称").result("执行者名称", Type.STRING)
        actions += Action.new(game, "切换执行者", "switch")
            .addEntry("玩家名或console", Type.STRING)
            .description("切换脚本执行者为指定玩家或控制台")
        actions += Action.new(game, "播放音效", "sound")
            .addEntry("音效名称", Type.STRING)
            .addEntry("音量", Type.FLOAT, true, head = "by")
            .addEntry("音调", Type.FLOAT, true)
            .description("向执行者播放音效，by/with 后接音量和音调（float）").example("sound ENTITY_EXPERIENCE_ORB_PICKUP by 1.0 1.0")
        actions += Action.new(game, "停止音效", "stopsound")
            .addEntry("音效名称", Type.STRING).description("停止播放指定音效")
        actions += Action.new(game, "执行命令", "command")
            .addEntry("命令内容", Type.STRING)
            .addEntry("执行方式(player/op/operator/console/server)", Type.STRING, true, head = "as")
            .description("执行命令，支持 by/with/as 关键字指定执行方式").example("command \"say hello\" as console")
        actions += Action.new(game, "玩家属性", "player")
            .addEntry("属性名", Type.STRING)
            .addEntry("操作(to/=/add/+/sub/-)", Type.STRING, true)
            .addEntry("值", Type.ANY, true)
            .description("读写玩家属性（57个属性），支持 to/=/add/increase/+/sub/decrease/- 操作").result("属性值", Type.ANY)
            .example("player health").example("player health to 20").example("player food_level add 5")
        actions += Action.new(game, "构建Location", "loc")
            .addEntry("世界名", Type.STRING).addEntry("X坐标", Type.DOUBLE)
            .addEntry("Y坐标", Type.DOUBLE).addEntry("Z坐标", Type.DOUBLE)
            .addEntry("Yaw", Type.FLOAT, true, head = "and")
            .addEntry("Pitch", Type.FLOAT, true)
            .description("构建 Location 对象，别名 location").result("Location", Type.ANY)
            .example("loc \"world\" 0 64 0").example("loc \"world\" 0 64 0 and 90 0")
        actions += Action.new(game, "计分板", "scoreboard")
            .addEntry("内容列表或null", Type.ANY)
            .description("向执行者发送计分板")
        actions += Action.new(game, "创建物品", "itemstack")
            .addEntry("材质名", Type.STRING).description("创建 ItemStack 对象").result("ItemStack", Type.ITEM_STACK)
        actions += Action.new(game, "获取材质", "material")
            .addEntry("材质名", Type.STRING).description("获取 Material 枚举").result("Material", Type.ANY)
        actions += Action.new(game, "PAPI变量", "papi")
            .addEntry("变量文本", Type.STRING)
            .description("解析 PlaceholderAPI 变量，别名 placeholder").result("解析结果", Type.STRING)
            .example("papi \"%player_name%\"")
        // ========== 脚本引擎 ==========
        val script = "Kether原生-脚本"
        actions += Action.new(script, "JavaScript脚本", "js")
            .addEntry("脚本内容", Type.STRING)
            .description("执行 JavaScript 脚本，别名 \$/javascript").result("脚本返回值", Type.ANY)
        actions += Action.new(script, "JEXL3脚本", "invoke")
            .addEntry("脚本内容", Type.STRING)
            .description("执行 JEXL3 脚本，支持 invoke dynamic <action>").result("脚本返回值", Type.ANY)
        // ========== 原版 ScriptProperty ==========
        val properties = ScriptManager.wikiProperties

        properties += Property.new("Kether原生-属性", "String", "string.operator")
            .description("字符串属性操作")
            .addEntry("upper", Type.STRING, "转大写，别名 uppercase")
            .addEntry("lower", Type.STRING, "转小写，别名 lowercase")
            .addEntry("length", Type.INT, "字符串长度，别名 size")
            .addEntry("trim", Type.STRING, "去除首尾空白")

        properties += Property.new("Kether原生-属性", "List", "list.operator")
            .description("列表属性操作，支持按数字索引读写元素")
            .addEntry("<索引>", Type.ANY, "按索引读写元素", true)
            .addEntry("length", Type.INT, "列表长度，别名 size")

        properties += Property.new("Kether原生-属性", "Map", "map.operator")
            .description("Map属性操作，支持按 @key 读写键值对")
            .addEntry("@<key>", Type.ANY, "按键名读写值，写入 null 时删除该键", true)
            .addEntry("length", Type.INT, "Map大小，别名 size")
            .addEntry("keys", Type.ITERABLE, "所有键的集合")
            .addEntry("values", Type.ITERABLE, "所有值的集合")

        properties += Property.new("Kether原生-属性", "Array", "array.operator")
            .description("数组属性操作，支持按数字索引读写元素")
            .addEntry("<索引>", Type.ANY, "按索引读写元素", true)
            .addEntry("length", Type.INT, "数组长度，别名 size")

        properties += Property.new("Kether原生-属性", "ItemStack", "item.operator")
            .description("物品堆属性操作")
            .addEntry("type", Type.STRING, "材质类型，别名 material", true)
            .addEntry("meta", Type.ANY, "ItemMeta 对象，别名 itemmeta", true)
            .addEntry("data", Type.INT, "耐久/数据值，别名 damage/durability", true)
            .addEntry("name", Type.STRING, "显示名称", true)
            .addEntry("lore", Type.ITERABLE, "Lore 列表", true)

        properties += Property.new("Kether原生-属性", "ItemMeta", "itemMeta.operator")
            .description("物品Meta属性操作")
            .addEntry("name", Type.STRING, "显示名称", true)
            .addEntry("lore", Type.ITERABLE, "Lore 列表", true)

        properties += Property.new("Kether原生-属性", "Matcher", "matcher.operator")
            .description("正则匹配结果属性操作")
            .addEntry("<数字>", Type.STRING, "按索引获取捕获组")
            .addEntry("<名称>", Type.STRING, "按名称获取命名捕获组")
    }
}
