package org.gitee.orryx.module.wiki

enum class Type {

    ITERABLE, CONTAINER, HITBOX, TARGET, STATE, EFFECT, EFFECT_SPAWNER, BYTE, SHORT, INT, LONG, DOUBLE, FLOAT, SYMBOL, STRING, BOOLEAN, VECTOR, MATRIX, QUATERNION, ITEM_STACK, ANY, NULL;
}