package org.gitee.orryx.module.wiki

enum class Type {
    ITERABLE, CONTAINER, TARGET, EFFECT, EFFECT_SPAWNER, BYTE, SHORT, INT, LONG, DOUBLE, FLOAT, SYMBOL, STRING, BOOLEAN, VECTOR, MATRIX, ITEM_STACK, ANY, NULL;
}