package org.gitee.orryx.core.wiki

enum class Type {
    ITERABLE, CONTAINER, TARGET, EFFECT, EFFECT_SPAWNER, INT, LONG, DOUBLE, FLOAT, SYMBOL, STRING, BOOLEAN, VECTOR, MATRIX, ITEM_STACK, ANY, NULL;
}